language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS searchable_test;'

before_script:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit
